init:
    admin:
        password: ENC(6kKAizMSawdVk4cAdzwVsnNylJtvlSGpgtnNcfZN1uRHvnmaqdrGwsj2cjd02XvR)
        username: ENC(Tkuhfp9rzmv1qJq1OpPObDKWGADPMTnTL9jrq2HV9NVp06HyWEGRckGUrVbGA1JZpl8OBgyBQlQgKQv+1cNWUA==)
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ENC(Ac5vC6XjIGtAfVjKSduzGKcvQH2xpD8f0iKYKWjLEKSPMb2I5kEH6hASLfi8TC6TtlCeC8dGXrA4tWKlMh+H/1FndPEYpPRX/O9+R/yYUNqZSrb0YY0MXz9mSxFT/LlChCF+sG+5F4vAIPFivE/Q9Q==)
        url: ENC(PFQsGd4eyYzGvSNa9KH7Zqduc1hPeUWzStTQVpMLYZfnPMytVOoO9xpiOiTSgISa9pGHLI8Y7K9sWoc+BEuUSO7srKG0psppxSx4LH8xgRO2GPSVv7koqNbYHfrEGXzbScBXCYxszHCjkCmwhNBwMzAknZiW5yVWgZMSJuBBlwSFSmXO+vAZpIasOz2GurWL)
        username: ENC(9xhPGG0PxKvIJTBq4YSRK6yXEzCzg3h+A4bYZKhBdfKmCgCEhDuKgQ8g0pRRHLZV)
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
#                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: false


#
# ./mvnw jasypt:encrypt-value -Djasypt.plugin.value= -Djasypt.encryptor.password=
# ./mvnw jasypt:decrypt-value -Djasypt.plugin.value= -Djasypt.encryptor.password=