jwt:
    refresh:
        token:
            exppiration: 604800000
    secret-key: ENC(ntZL1NceyFZ2AZ4SzT80xrty8ThW/MFkosMjFX6JbTYMlg3JmRFAHwrw9C/1xLcRwyQMG8KVbsKDdHtbhCsQtzdQk0UnUB4ldU1U4Onndj5YwBwP2vpbo3rK5fTZ2QhD0LFjgQMwLVi1KiPpWqQskg==)
    token:
        expiration: 86400000
paypal:
    client:
        id: AbTQsSjyfc8z-qi0JqOTl1h9qxfLKEct66abiSXIFvKLR7hWBQaXwG3zkMwekSrKL0jeH6KH-HKjzh8n
        secret: EBMPO4Y5lfNmXrG4UBdMhpq29YXOXq4pdK9l991CuIoBQxobrtgXUXP0yQuQzp2JnoS_WNRaqAKXGI9w
    mode: sandbox
server:
    port: 8081
    servlet:
        context-path: /jspace-service
spring:
    application:
        name: jspace-service
    jpa:
        properties:
            hibernate:
                jdbc:
                    time_zone: Asia/Ho_Chi_Minh
    profiles:
        active: aiven
